### PR TITLE
update from AA email

### PR DESCRIPTION
**Pull request by dangunter**
This doc. seems out of date. If this is not even the most current copy of the doc (?!) then we should delete it.

### CODE REVIEW

**Comment by nlharris** [comment]
Why do you think there might be a more current version of this doc?

Once we've resolved that, I would like to add text about the PR-approval process. (It's alluded to in the added text but not actually explained.)

**Comment by dangunter** [comment]
I am just a suspicious person. Yes, please feel free to edit @fperez would no doubt be glad to get the help.

**Comment by nlharris** [comment]
Ok, should we merge your PR first and then I'll edit from there?

**Comment by fperez** [comment]
Note that this PR seems to have been made from an out-of-date repo, it doesn't merge without conflicts... Needs a fix/rebase before it can be merged. Let me know if you need  a hand with that.

**Comment by nlharris** [comment]
Dan, I'm not sure what's going on here, I'm hoping you can detangle this mess.

**Comment by fperez** [comment]
It's a merge conflict, it needs a rebase.

**Comment by dangunter** [comment]
Would be easier to drop it and try again from the email, I think it's only
5-10 lines of new text.

# [Dan Gunter](http://bit.ly/1f4kXVW

http://xkcd.com/1525/#eyJxIjoid2lsbCBpIGZpbmQgaGFwcGluZXNzIiwiYSI6WyImI3gxRjZBRTsiXX0=)

**Comment by fperez** [comment]
Closing here in favor of #51, please let me know if that does the job and we can merge that instead then.

**Pull request closed without merging**
