### PR TITLE
Update Process_guide.md

### PR DESCRIPTION
**Pull request by kkellerlbl**
I would like to give more details about KBaseIncubator here.  But I also want to wait till we know how we're configuring it.  (I'm guessing we are going to stick with what we have now, where members can create repos.)  Two guidelines I'd like to mention are: 1) no repo from KBaseIncubator will ever be deployed to production, repos must be in the KBase org to be in production; 2) please be neat in KBaseIncubator, delete or move to your personal account repositories that are no longer active.

### CODE REVIEW

**Comment by mlhenderson** [comment]
So KBaseIncubator is where you do KBase work that will not be deployed.  If you were prototyping something I could see that, although there are certainly repos in the KBase org that don't get deployed, so I'm wondering if we need to rethink this going forward.  If you are working on something for KBase, we're assuming that you were assigned this work, or at least that you discussed it with your team lead and they approved it.  It seems like that generating your own repos in KBaseIncubator is a bit outside of the normal process, just trying to figure out how to align it.  Technically much of next-gen work will probably happen without production deploys for a while, so somehow we should reconcile how those types of work areas should fit.

**Comment by aparkin** [comment]
I agree. What ia the thought here?

Sent from mobile device and I have clumsy fingers.

On Tue, Apr 14, 2015 at 3:38 PM -0700, "Matt Henderson" notifications@github.com wrote:

So KBaseIncubator is where you do KBase work that will not be deployed.  If you were prototyping something I could see that, although there are certainly repos in the KBase org that don't get deployed, so I'm wondering if we need to rethink this going forward.  If you are working on something for KBase, we're assuming that you were assigned this work, or at least that you discussed it with your team lead and they approved it.  It seems like that generating your own repos in KBaseIncubator is a bit outside of the normal process, just trying to figure out how to align it.  Technically much of next-gen work will probably happen without production deploys for a while, so somehow we should reconcile how those types of work areas should fit.

**Comment by kkellerlbl** [comment]
The original idea behind incubator was that it was a sandbox/prototype area for alpha-quality code (or less) that wasn't yet ''officially'' part of KBase, without having to put the repo into your personal account.  
So it's not just that the repo isn't currently deployed, it's that as a policy we would not ever deploy code from incubator into production.  (In theory we could deploy undeployed repos in the KBase org into production.  I imagine some of it doesn't work; those repos could be moved to incubator if we wanted.)

The KBaseIncubator org has existed for quite a while already, I just wanted to get it mentioned in the docs.  But we can also simply decide not to use incubator at all.

**Comment by mlhenderson** [comment]
I think we should seriously consider not using incubator at all.  If you want to mess around on your own time you would use your personal github.  If you're doing it on KBase time then it must be assigned or at least approved, which means it lives in the KBase org.  Sure we'll have some transient repos that don't work out maybe, but that's not a problem as long as they are removed.  They don't get deployed to production, so no harm no foul.

Another possible consideration is having an org for community contributions to KBase that would not be supported by KBase developers or deployed into production.  They could eventually be absorbed into KBase proper in some form if they meet the KBase criteria and reach a critical mass (TBD).

**Comment by kkellerlbl** [comment]
I have no strong opinion.  Let's bounce it around tomorrow and see what
people think.

-k

## 

Keith Keller
Physical Biosciences Division
(sent from mobile)

**Comment by aparkin** [comment]
One possible use of Incubator is queuing things up that are from external
developers but are slated for later in the roadmap.
If you look at the guide for external developers we are going to be asking
they create a clean repo with code, data and documents.

On Tue, Apr 14, 2015 at 7:15 PM, kkellerlbl notifications@github.com
wrote:

> I have no strong opinion. Let's bounce it around tomorrow and see what
> people think.
> 
> -k
> 
> ## 
> 
> Keith Keller
> Physical Biosciences Division
> (sent from mobile)
> On Apr 14, 2015 6:56 PM, "Matt Henderson" notifications@github.com
> wrote:
> 
> > I think we should seriously consider not using incubator at all. If you
> > want to mess around on your own time you would use your personal github.
> > If
> > you're doing it on KBase time then it must be assigned or at least
> > approved, which means it lives in the KBase org. Sure we'll have some
> > transient repos that don't work out maybe, but that's not a problem as
> > long
> > as they are removed. They don't get deployed to production, so no harm no
> > foul.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kbase/project_guides/pull/10#issuecomment-93145545.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kbase/project_guides/pull/10#issuecomment-93153881.

## 

Adam Paul Arkin

## Dean A. Richard Newton Memorial Chair

Director, Physical Biosciences Division
E.O. Lawrence Berkeley National Laboratory

Professor, Department of Bioengineering
University of California
Berkeley, CA, 94720

CEO/CSO, DOE Systems Biology Knowledgebase, http://kbase.us
Director, Berkeley Synthetic Biology Institute, http://synbio.berkeley.edu
PI and Co-Director, ENIGMA SFA, http://enigma.lbl.gov http://vimss.lbl.gov
Investigator, Energy Biosciences Institute,
http://energybiosciencesinstitute.org

Office: 512C Energy Biosciences Building (Berkeley Campus)
Mailing address:
E.O. Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 955-512L
Berkeley, CA 94720

Contact:
W: http://genomics.lbl.gov
V: 510-495-2366
C: 510-206-1389
F: 510-486-6219

Assistant:
Gwyneth A. Terry
V: 510-495-2116

## E: GATerry@lbl.gov

**Comment by mlhenderson** [comment]
Ha, yeah I edited that into my comment, but that probably did not get sent
out.

**Comment by dangunter** [comment]
cf. external devs, it may help to (re-)consider the Apache Incubator process, which I assume the word "incubator" is alluding to. From their [web pages](http://incubator.apache.org/):

"The Incubator project is the entry path into The Apache Software Foundation (ASF) for projects and codebases wishing to become part of the Foundation's efforts. All code donations from external organisations and existing external projects wishing to join Apache enter through the Incubator. The Apache Incubator has two primary goals: Ensure all donations are in accordance with the ASF legal standards; Develop new communities that adhere to our guiding principles"

This seems, to me, like a reasonable use of the KBase Incubator as well. That said, we are not ready for many external collaborations (too busy propping up our own stuff), so I would put this whole activity as low-priority for now.

**Comment by cshenry** [comment]
I honestly wanted to have an environment where cutting edge features would be deployed as part of our science engagement effort so our collaborators could try them out and provide feedback without having to deploy to production or dev (as dev is really all about staging for production). It doesn't sound like this is kbase incubator though. Do we have such an environment, with associated branches in the standard kbase repos? Is it "next" or "CI"?

**Comment by kkellerlbl** [comment]
I don't think we currently have a beta-test environment that we can let users experiment with.  It's definitely not -next, that should be for services that are imminent for deployment to production.  I don't think it's -ci, I think that's for testing services so that they can be approved for testing in -next.  And it's not narrative-dev, which is no longer for staging to production, but for narrative developers (not service devs).

**Comment by fperez** [comment]
I agree with folks above that incubator process and some kind of realistic playground for science engagement are both valuable but distinct.

I think we should make two independent decisions:
1. Should we have an 'incubator' org at all, and if so, what should it look like? I would say that if we do, we should as @dangunter pointed out, just follow the Apache model, which for this I think is more than fine.  Incubator would then be a place where projects can gradually test their process, validate license/data compliance, establish testing/docs practices, etc.
2. Should we have a _runtime_ environment that is as realistic as possible for testing of new deployed services, as @cshenry asks?  This one, I'd actually break down int two:

a) Make it very, very easy to deploy a collection of docker containers in one or two VMs that is a minimal, but operational, KBase.  If this were much easier, we could much more simply point potential new collaborators to that process as a way to validate their tools, without requiring direct involvement of KBase staff/resources.

b) Having a KBase-staffed runtime with resources for the above.

I have a very strong preference for (a) instead of (b), since b bottlenecks on our people/resources.  But I also realize that right now, (b) may be more realistic than (a), so if this is considered to be a critical need, then the devops folks (Shane, Dan, etc) will need to be part of the conversation.

**Comment by brettin** [comment]
Some of the original thinking behind the Incubator was modeled after our understanding of the Apache Incubator. It was envisioned that the project, both internal staff and external contributors, needed a place where they could explore new ideas, where creativity could take place, without cluttering up the github kbase organization. Prior to the move to github, the git.kbase.us server became cluttered, with repos created for testing new deployment strategies, repose that were never used, etc. So an attempt to separate high risk or temporary ideas from those that represented modules required in some way for the system to operate. 

The original ideas behind the incubator were also not well polished, just that it was simply recognized that a place to explore new codes was needed. It was also not envisioned that ALL activities  needed to be assigned, or vetted with a box lead (these are new concepts in the project). A pleasant way to think about it might be Google Friday. Freedom to innovate and create and yet meet project requirements and deliverables (Mon-Thur). Hence, the incubator.

In any case, I just wanted to provide some of the thoughts behind the incubator that existed in the past.

**Comment by dangunter** [comment]
As the purpose of the Apache Incubator is quite different than what Tom
described for KBase, it is indeed helpful to get a clear description of
what KBase really meant by "incubator". I wouldn't advocate continuing the
incubator in either mode, for now. The Apache mode could be reconsidered
once we could actually add external code without deep collaboration.

# [Dan Gunter](http://acs.lbl.gov/~dang)

**Comment by kkellerlbl** [comment]
Should we reject this PR then?

**Comment by mlhenderson** [comment]
I think we should close the PR and revisit the Incubator concept at a later date.  I think that is in agreement with Dan G?

**Comment by kkellerlbl** [comment]
Closing this PR.

**Comment by fperez** [comment]
OK to delete the branch? I assume folks have that branch in their local copy, we don't want the main repo to grow a bunch of unused branches...

I'll wait 24h and delete unless someone complains. If you'd like to have these commits, please keep a local reference to the branch in your fork.

**Comment by kkellerlbl** [comment]
If the edit were important enough I'd keep it, but this is so trivial I don't care if it's lost.  So feel free to delete the branch.

Will deleting the branch also delete the PR and discussion?  The discussion is more valuable than the edit, honestly.

**Comment by fperez** [comment]
Nope, branch deletion doesn't delete the discussion, which is indeed the more valuable information.  It just cleans up the visible branches in the main repo, that's all.

Cleaning now then. Thanks!

**Pull request closed without merging**
