### PR TITLE
Template for KBase Science Narratives

### PR DESCRIPTION
**Pull request by hhaun**
Created a new project guide that provides a template for science Narratives

### CODE REVIEW

**Comment by nlharris** [comment]
Looks good to me!

**Comment by dangunter** [comment]
An incidental thought (_not_ something needing to be addressed before merge), is that there could be a feature in the UI that created new Narratives starting with this template (or is this already the plan?). @briehl: eventually this could even expand to user-defined templates, stored in the profile, but step one would be expanding the "New Narrative" button to have multiple options rather than just one (sort of like the Google Drive "New" button).

**Comment by nlharris** [comment]
Interesting idea, @dangunter, as a future enhancement.

**Comment by nlharris** [comment]
@bobcottingham, can you merge this PR?

**Comment by scanon** [comment]
I like the template idea too.  We should make a note of that.

**Comment by nlharris** [comment]
If there are no objections to the content of this template, could someone please merge the PR?

**Comment by nlharris** [comment]
I now have merge permission, so I am merging this. Feel free to comment or suggest changes (via PRs).

**Pull request merged**
