### PR TITLE
[WIP] Remaining questions from previous PR

### PR DESCRIPTION
**Pull request by fperez**
Note, the body of the PR is not really meant for merging as-is, only to record the start of the discussion.

These are a few questions that arose in the previous PR #55, regarding how the Agile
development process and decisions are made.  

I wanted to make sure we didn't drop them, so we can clarify them, even if in the end, this document isn't the final place to discuss them all.
1. A request for more transparency from EC on decision process: agenda and
   outcomes, as they pertain to the development process, should be shared with
   the team.
2. How is work outside of the sprint cycles reported, managed, or decided on? 
3. Does the Executive committee review work that is not part of the sprint
   cycles? 
4. How do the working teams get a finer-granularity and updated description of
   priorities and project vision? This seems critically necessary to have clear
   objectives and goals that to plan against.  Basically, a dynamic, living
   version of the project high-level roadmap that is updated periodically by the
   EC.

### CODE REVIEW

**Comment by fperez** [comment]
BTW, I'm going to be extremely unavailable for the next 3 weeks, so folks should feel free to continue the discussion without me.   Given that this PR is more of a placeholder for conversation, a real PR with content could be made by someone else off a different branch if that's better.

**Comment by dangunter** [comment]
If it is up to a given self-organized group of developers what to do during a sprint cycle, then everyone should participate equally in the sprint reviews. I am including myself and arch-dev. Put another way, transparency should not be a punishment for being part of production.

**Comment by mlhenderson** [comment]
Thanks @fperez for making sure these items don't get lost.  @aparkin How do we work on these items with the EC and PIs?

**Comment by aparkin** [comment]
@mlhenderson I think I need to work these through with you. I am not sure all of what is being requested. 

A request for more transparency from EC on decision process: agenda and
outcomes, as they pertain to the development process, should be shared with
the team.

--> Right now It is still unclear that the exec IS making any decisions. The ideally we would start with the diagram in the proposal and sprint proposals would line themselves up with boxes on that diagram 
The EC would then evaluate whether each sprint actually did meet that box goal; if it was a signifcant priority compared to others; and rate it against thing that come up that are "surprises" that need to be dealt with. At the moment there is also always resource issues: we have to balance user growth with needed development and individual team interests and talents and it makes some decision making difficult. 
But if we could create such a clean document the decision making proccess could be more transparent. 

How is work outside of the sprint cycles reported, managed, or decided on?

Theoretically I think all projects should report on the sprint cycle directly. All should be using GitHub (this IS outlined in the process guide) and decisions are made by a similar process as sprints but on a different time scale. 

Does the Executive committee review work that is not part of the sprint
cycles?

Yes, 

How do the working teams get a finer-granularity and updated description of
priorities and project vision? This seems critically necessary to have clear
objectives and goals that to plan against. Basically, a dynamic, living
version of the project high-level roadmap that is updated periodically by the
EC.

Well-- the EC relies in part on the team to help us make this finer-granuarity. We have a self-consistent field to come to.. we want: better documentation, more user testing, easier development, more functionality, better rendered current functionality, more responsiveness of the system; more data types; etc. We have no magic formula to figure out how to array resources to meet these goals and prioritize from the top because whatever I or others on the EC might thing we might not have the immediate resources who are interested/willing/able to do X especially when Y is also a priority. But I think if we can get the Jira system set up to respect the roadmap I talked about above-- and we can break that roadmap into slightly finer granularity (e.g. UE discussing the need for narratorial development, etc.) then I think this can become easier.

**Pull request merged**
